export type GarmentType = 'top' | 'bottom' | 'dress' | 'full_outfit'

export interface Product {
  id: string
  name: string
  brand: string
  price: number
  originalPrice?: number
  category: 'women' | 'men'
  subcategory: string
  garmentType: GarmentType
  colors: { name: string; hex: string }[]
  sizes: string[]
  badge?: 'NEW' | 'SALE' | 'HOT' | 'LIMITED'
  rating: number
  reviewCount: number
  images: string[]
  description: string
  details: string[]
  material: string
  inStock: boolean
}

export const products: Product[] = [
  // ─── Women · Top ───
  {
    id: 'wt01',
    name: 'Lace-Trim Stripe Blouse',
    brand: 'LUMIÈRE',
    price: 165,
    category: 'women',
    subcategory: 'Tops',
    garmentType: 'top',
    colors: [
      { name: 'Cream', hex: '#F5F0E8' },
      { name: 'Dusty Rose', hex: '#DCAE96' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: 'NEW',
    rating: 4.8,
    reviewCount: 72,
    images: ['/products/women/top/top01.jpg'],
    description: 'V-neck striped blouse with delicate crochet lace trim and pearl button details.',
    details: ['V-neckline', 'Crochet lace inserts', 'Pearl buttons', 'Cap sleeves'],
    material: '100% Cotton',
    inStock: true,
  },
  {
    id: 'wt02',
    name: 'Ruched Off-Shoulder Top',
    brand: 'LUMIÈRE',
    price: 142,
    category: 'women',
    subcategory: 'Tops',
    garmentType: 'top',
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Noir', hex: '#1A1A1A' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 58,
    images: ['/products/women/top/top02.webp'],
    description: 'Feminine ruched top with off-shoulder neckline. Perfect for summer evenings.',
    details: ['Off-shoulder design', 'Ruched body', 'Stretch fabric', 'Cropped length'],
    material: '92% Cotton, 8% Elastane',
    inStock: true,
  },
  {
    id: 'wt03',
    name: 'Oversized Graphic Tee',
    brand: 'LUMIÈRE SPORT',
    price: 98,
    category: 'women',
    subcategory: 'Tops',
    garmentType: 'top',
    colors: [
      { name: 'Vintage White', hex: '#FAF9F6' },
      { name: 'Washed Black', hex: '#3D3D3D' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: 'HOT',
    rating: 4.5,
    reviewCount: 143,
    images: ['/products/women/top/top03.webp'],
    description: 'Relaxed-fit graphic tee with artistic print. Streetwear meets art.',
    details: ['Oversized fit', 'Graphic print', 'Ribbed crew neck', 'Drop shoulder'],
    material: '100% Cotton',
    inStock: true,
  },
  {
    id: 'wt04',
    name: 'Crochet Halter Top',
    brand: 'LUMIÈRE',
    price: 185,
    category: 'women',
    subcategory: 'Tops',
    garmentType: 'top',
    colors: [
      { name: 'Sage', hex: '#B2AC88' },
      { name: 'Cream', hex: '#FFFDD0' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.7,
    reviewCount: 89,
    images: ['/products/women/top/top04.webp'],
    description: 'Hand-crocheted halter top with bohemian charm. A festival essential.',
    details: ['Hand crocheted', 'Halter neckline', 'Tie-back closure', 'Cropped fit'],
    material: '100% Cotton Yarn',
    inStock: true,
  },
  {
    id: 'wt05',
    name: 'Structured Crop Blazer',
    brand: 'LUMIÈRE',
    price: 318,
    category: 'women',
    subcategory: 'Tops',
    garmentType: 'top',
    colors: [
      { name: 'Charcoal', hex: '#36454F' },
      { name: 'Ivory', hex: '#FFFFF0' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'LIMITED',
    rating: 4.9,
    reviewCount: 46,
    images: ['/products/women/top/top05.webp'],
    description: 'Precision-tailored cropped blazer. Power dressing redefined.',
    details: ['Cropped length', 'Padded shoulders', 'Single button', 'Italian wool blend'],
    material: '72% Wool, 28% Polyester',
    inStock: true,
  },

  // ─── Women · Bottom ───
  {
    id: 'wb01',
    name: 'Balloon Parachute Pants',
    brand: 'LUMIÈRE SPORT',
    price: 208,
    category: 'women',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Burgundy', hex: '#800020' },
      { name: 'Noir', hex: '#1A1A1A' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    badge: 'HOT',
    rating: 4.7,
    reviewCount: 167,
    images: ['/products/women/bottom/bottom01.webp'],
    description: 'Oversized balloon-leg parachute pants with elasticated waist. Comfort meets style.',
    details: ['Balloon silhouette', 'Elastic waist', 'Side logo', 'Floor-length'],
    material: '80% Cotton, 20% Polyester',
    inStock: true,
  },
  {
    id: 'wb02',
    name: 'Pleated Wide-Leg Trousers',
    brand: 'LUMIÈRE',
    price: 240,
    category: 'women',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Khaki', hex: '#C3B091' },
      { name: 'Navy', hex: '#000080' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: 'NEW',
    rating: 4.8,
    reviewCount: 93,
    images: ['/products/women/bottom/bottom02.webp'],
    description: 'High-waisted pleated trousers with elegant wide-leg silhouette.',
    details: ['High waist', 'Front pleats', 'Wide leg', 'Ankle length'],
    material: '68% Viscose, 32% Linen',
    inStock: true,
  },
  {
    id: 'wb03',
    name: 'Cargo Utility Pants',
    brand: 'LUMIÈRE SPORT',
    price: 185,
    category: 'women',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Olive', hex: '#808000' },
      { name: 'Noir', hex: '#1A1A1A' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    rating: 4.5,
    reviewCount: 78,
    images: ['/products/women/bottom/bottom03.webp'],
    description: 'Multi-pocket cargo pants with adjustable cuffs. Street-ready utility.',
    details: ['Multi-pocket', 'Adjustable cuffs', 'Relaxed fit', 'Cotton twill'],
    material: '100% Cotton Twill',
    inStock: true,
  },
  {
    id: 'wb04',
    name: 'Tailored Slim Trousers',
    brand: 'LUMIÈRE',
    price: 219,
    category: 'women',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Camel', hex: '#C19A6B' },
      { name: 'Noir', hex: '#1A1A1A' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    rating: 4.6,
    reviewCount: 112,
    images: ['/products/women/bottom/bottom04.webp'],
    description: 'Classic tailored slim-fit trousers for a polished office look.',
    details: ['Slim fit', 'Invisible zip', 'Stretch comfort', 'Full length'],
    material: '64% Polyester, 34% Viscose, 2% Elastane',
    inStock: true,
  },
  {
    id: 'wb05',
    name: 'Flared Denim Jeans',
    brand: 'LUMIÈRE',
    price: 175,
    originalPrice: 230,
    category: 'women',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Light Wash', hex: '#A4C8E1' },
      { name: 'Indigo', hex: '#3F51B5' },
    ],
    sizes: ['24', '25', '26', '27', '28', '29', '30'],
    badge: 'SALE',
    rating: 4.4,
    reviewCount: 205,
    images: ['/products/women/bottom/bottom05.webp'],
    description: '70s-inspired high-rise flared jeans. Retro vibes, modern fit.',
    details: ['High rise', 'Flared leg', 'Vintage wash', '5-pocket style'],
    material: '99% Cotton, 1% Elastane',
    inStock: true,
  },

  // ─── Women · Dress ───
  {
    id: 'wd01',
    name: 'Tiered Maxi Dress',
    brand: 'LUMIÈRE',
    price: 360,
    category: 'women',
    subcategory: 'Dresses',
    garmentType: 'dress',
    colors: [
      { name: 'Olive', hex: '#6B7B3A' },
      { name: 'Terracotta', hex: '#CC5500' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: 'NEW',
    rating: 4.9,
    reviewCount: 84,
    images: ['/products/women/dress/dress01.webp'],
    description: 'Romantic tiered maxi dress with smocked bodice and button-front detail.',
    details: ['Smocked bodice', 'Tiered skirt', 'Button front', 'Cap sleeves'],
    material: '100% Cotton Voile',
    inStock: true,
  },
  {
    id: 'wd02',
    name: 'Silk Slip Midi Dress',
    brand: 'LUMIÈRE',
    price: 318,
    originalPrice: 418,
    category: 'women',
    subcategory: 'Dresses',
    garmentType: 'dress',
    colors: [
      { name: 'Champagne', hex: '#F7E7CE' },
      { name: 'Midnight', hex: '#191970' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: 'SALE',
    rating: 4.8,
    reviewCount: 96,
    images: ['/products/women/dress/dress02.webp'],
    description: 'Bias-cut silk slip dress with adjustable straps. Effortlessly elegant.',
    details: ['100% silk twill', 'Bias-cut', 'Adjustable straps', 'Midi length'],
    material: '100% Silk',
    inStock: true,
  },
  {
    id: 'wd03',
    name: 'Bohemian Wrap Dress',
    brand: 'LUMIÈRE',
    price: 275,
    category: 'women',
    subcategory: 'Dresses',
    garmentType: 'dress',
    colors: [
      { name: 'Sage Green', hex: '#B2AC88' },
      { name: 'Dusty Rose', hex: '#DCAE96' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 128,
    images: ['/products/women/dress/dress03.webp'],
    description: 'Flowy wrap dress with botanical print. Bohemian elegance for any occasion.',
    details: ['Wrap silhouette', 'V-neckline', 'Tie waist', 'Knee length'],
    material: '100% Viscose',
    inStock: true,
  },
  {
    id: 'wd04',
    name: 'Knit Bodycon Dress',
    brand: 'LUMIÈRE',
    price: 208,
    category: 'women',
    subcategory: 'Dresses',
    garmentType: 'dress',
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Camel', hex: '#C19A6B' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: 'HOT',
    rating: 4.6,
    reviewCount: 174,
    images: ['/products/women/dress/dress04.webp'],
    description: 'Figure-hugging ribbed knit dress. Minimalist chic for day to night.',
    details: ['Ribbed knit', 'Bodycon fit', 'Midi length', 'Crew neck'],
    material: '70% Viscose, 30% Polyester',
    inStock: true,
  },
  {
    id: 'wd05',
    name: 'Embroidered Linen Dress',
    brand: 'LUMIÈRE',
    price: 405,
    category: 'women',
    subcategory: 'Dresses',
    garmentType: 'dress',
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Sky Blue', hex: '#87CEEB' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    badge: 'LIMITED',
    rating: 5.0,
    reviewCount: 32,
    images: ['/products/women/dress/dress05.webp'],
    description: 'Hand-embroidered linen maxi dress. Artisanal craftsmanship meets modern design.',
    details: ['Hand embroidered', 'Pure linen', 'Maxi length', 'Side pockets'],
    material: '100% French Linen',
    inStock: true,
  },

  // ─── Men · Top ───
  {
    id: 'mt01',
    name: 'Graphic Art Tee',
    brand: 'LUMIÈRE SPORT',
    price: 98,
    category: 'men',
    subcategory: 'T-Shirts',
    garmentType: 'top',
    colors: [
      { name: 'Washed Purple', hex: '#7B68AE' },
      { name: 'Faded Black', hex: '#3D3D3D' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    badge: 'NEW',
    rating: 4.5,
    reviewCount: 189,
    images: ['/products/men/top/top11.webp'],
    description: 'Vintage-wash graphic tee with hand-drawn art print. Casual perfection.',
    details: ['Vintage wash', 'Hand-drawn graphic', 'Relaxed fit', 'Ribbed collar'],
    material: '100% Cotton',
    inStock: true,
  },
  {
    id: 'mt02',
    name: 'Structured Oxford Shirt',
    brand: 'LUMIÈRE',
    price: 165,
    category: 'men',
    subcategory: 'Shirts',
    garmentType: 'top',
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Light Blue', hex: '#ADD8E6' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 156,
    images: ['/products/men/top/top12.webp'],
    description: 'Classic oxford shirt with modern slim fit. A wardrobe staple.',
    details: ['Button-down collar', 'Slim fit', 'Single pocket', 'Box pleat back'],
    material: '100% Oxford Cotton',
    inStock: true,
  },
  {
    id: 'mt03',
    name: 'Oversized Hoodie',
    brand: 'LUMIÈRE SPORT',
    price: 142,
    category: 'men',
    subcategory: 'Hoodies',
    garmentType: 'top',
    colors: [
      { name: 'Heather Grey', hex: '#B2BEB5' },
      { name: 'Noir', hex: '#1A1A1A' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    badge: 'HOT',
    rating: 4.8,
    reviewCount: 243,
    images: ['/products/men/top/top13.webp'],
    description: 'Premium heavyweight oversized hoodie. Cozy meets streetwear.',
    details: ['400gsm weight', 'Oversized fit', 'Kangaroo pocket', 'Ribbed cuffs'],
    material: '80% Cotton, 20% Polyester',
    inStock: true,
  },
  {
    id: 'mt04',
    name: 'Camp Collar Shirt',
    brand: 'LUMIÈRE',
    price: 185,
    category: 'men',
    subcategory: 'Shirts',
    garmentType: 'top',
    colors: [
      { name: 'Ecru Print', hex: '#F5F5DC' },
      { name: 'Navy Print', hex: '#000080' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.6,
    reviewCount: 91,
    images: ['/products/men/top/top14.webp'],
    description: 'Relaxed camp collar shirt with resort-inspired print. Weekend essential.',
    details: ['Camp collar', 'All-over print', 'Relaxed fit', 'Chest pocket'],
    material: '100% Rayon',
    inStock: true,
  },
  {
    id: 'mt05',
    name: 'Cashmere Crewneck',
    brand: 'LUMIÈRE',
    price: 250,
    category: 'men',
    subcategory: 'Knitwear',
    garmentType: 'top',
    colors: [
      { name: 'Oatmeal', hex: '#D4C5A9' },
      { name: 'Noir', hex: '#1A1A1A' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: 'LIMITED',
    rating: 4.9,
    reviewCount: 67,
    images: ['/products/men/top/top15.webp'],
    description: 'Mongolian Grade-A cashmere crewneck. Buttery soft luxury.',
    details: ['Grade-A cashmere', 'Ribbed trim', 'Regular fit', 'Mongolian origin'],
    material: '100% Cashmere',
    inStock: true,
  },

  // ─── Men · Bottom ───
  {
    id: 'mb01',
    name: 'Wide-Leg Tailored Trousers',
    brand: 'LUMIÈRE',
    price: 240,
    category: 'men',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Navy', hex: '#1B2A4A' },
      { name: 'Charcoal', hex: '#36454F' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    badge: 'NEW',
    rating: 4.8,
    reviewCount: 104,
    images: ['/products/men/bottom/bottom11.webp'],
    description: 'Wide-leg tailored trousers with front pleats. Modern elegance.',
    details: ['Wide leg', 'Front pleats', 'Side pockets', 'Full length'],
    material: '100% Wool',
    inStock: true,
  },
  {
    id: 'mb02',
    name: 'Relaxed Chino Pants',
    brand: 'LUMIÈRE',
    price: 175,
    category: 'men',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Khaki', hex: '#C3B091' },
      { name: 'Olive', hex: '#808000' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    rating: 4.6,
    reviewCount: 138,
    images: ['/products/men/bottom/bottom12.webp'],
    description: 'Relaxed-fit chino pants with soft hand feel. Everyday versatility.',
    details: ['Relaxed fit', 'Twill weave', 'Button closure', 'Tapered leg'],
    material: '98% Cotton, 2% Elastane',
    inStock: true,
  },
  {
    id: 'mb03',
    name: 'Cargo Jogger Pants',
    brand: 'LUMIÈRE SPORT',
    price: 153,
    category: 'men',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Army Green', hex: '#4B5320' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: 'HOT',
    rating: 4.5,
    reviewCount: 211,
    images: ['/products/men/bottom/bottom13.webp'],
    description: 'Technical cargo joggers with multiple pockets. Street-ready utility.',
    details: ['Elastic waist', 'Cargo pockets', 'Cuffed ankles', 'Drawstring hem'],
    material: '100% Nylon',
    inStock: true,
  },
  {
    id: 'mb04',
    name: 'Straight-Leg Denim',
    brand: 'LUMIÈRE',
    price: 198,
    category: 'men',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Raw Indigo', hex: '#3F51B5' },
      { name: 'Washed Black', hex: '#3D3D3D' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    rating: 4.7,
    reviewCount: 176,
    images: ['/products/men/bottom/bottom14.webp'],
    description: 'Classic straight-leg selvedge denim. Timeless Japanese denim.',
    details: ['Selvedge denim', 'Straight leg', 'Button fly', '14oz weight'],
    material: '100% Cotton Selvedge',
    inStock: true,
  },
  {
    id: 'mb05',
    name: 'Pleated Dress Pants',
    brand: 'LUMIÈRE',
    price: 275,
    category: 'men',
    subcategory: 'Trousers',
    garmentType: 'bottom',
    colors: [
      { name: 'Charcoal', hex: '#36454F' },
      { name: 'Cream', hex: '#FFFDD0' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    badge: 'SALE',
    originalPrice: 350,
    rating: 4.8,
    reviewCount: 62,
    images: ['/products/men/bottom/bottom15.webp'],
    description: 'Formal pleated dress pants with satin stripe. Black-tie ready.',
    details: ['Double pleats', 'Satin side stripe', 'Slim taper', 'Full length'],
    material: '100% Merino Wool',
    inStock: true,
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return products
  return products.filter(p => p.category === category)
}

export function getProductsByGarmentType(garmentType: GarmentType): Product[] {
  return products.filter(p => p.garmentType === garmentType)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter(p => p.id !== product.id && (p.category === product.category || p.garmentType === product.garmentType))
    .slice(0, limit)
}
